### ISSUE TITLE
small remark

### ISSUE THREAD

**Issue by pythononwheels** [karlseguin/the-little-mongodb-book#41]
Hi Karl,

I am currently working on the german translation of the book and just stumbled across this sentence right
before the chapter: getting started:

 > As you may have noticed, we use the terms MongoDB and Mongo interchangeably.

You did not use the term Mongo a single time before this sentence. So nobody
will have noticed that ;) 
In fact you never use the term Mongo as a synonym for MongoDB throughout the whole book.

The term mongo is (when it occurs) always use in combination with the mongo (client) shell.

So you could probably even delete the sentence. ;)

Kind regards,
Klaas

**Comment by karlseguin** [comment]
agree
