### ISSUE TITLE
System.indexes: Deprecated since version 3.0

### ISSUE THREAD

**Issue by neilmacintyre** [karlseguin/the-little-mongodb-book#44]
Some information on System.indexes is no longer relevant.

https://docs.mongodb.com/manual/reference/system-collections/

> By default, the _id field is indexed - which explains why the system.indexes collection was created. You can look at system.indexes:

> db.system.indexes.find()

**Comment by karlseguin** [comment]
Any thoughts on:
https://github.com/karlseguin/the-little-mongodb-book/commit/640e4e96d3ba7b797a4a3b07a508685eb00aa7bf

 ?

**Comment by neilmacintyre** [comment]
Looks good, thanks:)
