### ISSUE TITLE
This book has been plagiarised

### ISSUE THREAD

**Issue by jannewmarch** [karlseguin/the-little-mongodb-book#46]
Seyed Hossein Ahmadpanah has apparently done a ripoff of your book, publishing it under his name as "Start MongoDB". It has already been confirmed that he has pirated at least two others, out of the 24 he has claimed to write. If you confirm this, you may like to post a suitable review of his book on Amazon, etc, like I did for his plagiarised version of my Go Networking book. Or take other action as you see fit.

He is selling it on Amazon for $15 at https://www.amazon.com/Start-MongoDB-Seyed-Hossein-Ahmadpanah/dp/1511945060/ref=sr_1_19?s=books&ie=UTF8&qid=1495874548&sr=1-19&keywords=Seyed+Hossein+Ahmadpanah

**Comment by karlseguin** [comment]
Thanks. Appreciate the heads up. Not the first time for me. Amazon was unresponsive last time. Then I managed to get it viral enough for them to take care of it. Don't think I have the energy to strike gold twice, we'll see.

**Comment by ranman** [comment]
Hey I work for amazon now. I want to take care of this. Can you email me any relevant details? Randhunt@amazon.com

**Comment by karlseguin** [comment]
For mine. The unauthorized product URL is: https://www.amazon.com/Start-MongoDB-Seyed-Hossein-Ahmadpanah/dp/1511945060/ref=sr_1_1?s=books&ie=UTF8&qid=1495889095&sr=1-1&keywords=Start+MongoDB with a listed ISBN-10 of **1511945060**

The original is at: http://openmymind.net/mongodb.pdf

The license is one the second page (not including the cover page) and is a Creative Common  Attribution-NonCommercial 3.0. 

Ideally 1 violation is enough to shut it all down, but in addition to mine, there's Jan's book which appears to be: https://www.amazon.com/Start-Go-Seyed-Hossein-Ahmadpanah/dp/1511735163/ref=asap_bc?ie=UTF8

And, Jan also kindly opened https://github.com/hgducharme/SQL-Basics/issues/5 which I'd guess is: https://www.amazon.com/Start-SQL-Seyed-Hossein-Ahmadpanah/dp/1511852518/ref=asap_bc?ie=UTF8

**Comment by karlseguin** [comment]
BTW, thank you both.

**Comment by jannewmarch** [comment]
Dear Amazon

You sell about 20 books published under the claimed authorship of Seyed
Hossein Ahmadpanah. It has been confirmed by 7 of the original authors
that these are works plagiarised by Seyed, in contravention of their
copyright. I have also identified the probable origin of a further 13
books, including one that had its first edition back in 1976 by
Professor Niklaus Wirth!

The books are published by CreateSpace, which is a subsidiary of
Amazon.

All of the confirmed authors request that you remove the plagiarised
books by Seyed Hossein Ahmadpanah from your Amazon sales lists, and
that CreateSpace cease from distributing those books. The other
probable authors would most likely make the same request.

I have attached a document listing the books confirmed to be
plagiarised along with the titles used by Seyed, and the books also
claimed by him which are remarkably similar to earlier published books.

Regards

Jan
-- 
Dr Jan Newmarch,
Director of Higher Education (Business & ICT) @ Box Hill,
Adjunct Professor @ University of Canberra

P 61 3 9286 9971
M +61 4 0117 0509
F 61 3 9286 9100
W www.boxhill.edu.au
W jan.newmarch.name
E j.newmarch@boxhill.edu.au
E jan@newmarch.name

**Comment by ranman** [comment]
@jannewmarch do you have the document you're talking about?

**Comment by jannewmarch** [comment]
I don't have a copy of the book - I'm not going to give the plagiarist
any money! But look for "Start MongoDB" on Amazon, by  Seyed Hossein
Ahmadpanah. Then "Look inside" at "First pages". I did a google search
on the first line: "It's true that there is an ever growing list of new
technologies" (in quotes) and look what I found:

    The Little MongoDB Book - Karl Seguin
    openmymind.net/mongodb.pdf
    It's true that there is an ever growing list of new technologies and
    techniques being released. 

Jan
-- 
Dr Jan Newmarch,
Director of Higher Education (Business & ICT) @ Box Hill,
Adjunct Professor @ University of Canberra

**Comment by ranman** [comment]
This is what I meant:
"I have attached a document listing the books confirmed to be
plagiarised along with the titles used by Seyed,"

The document with the list of confirmed plagiarized articles.

**Comment by ranman** [comment]
FWIW I've started a ticket internally at Amazon and I'm working aggressively to get this guy removed from our site entirely.

**Comment by jannewmarch** [comment]
Hi
Github doesn't like attachements, I guess. I've put it on my web site
at https://jan.newmarch.name/PlagiarisedBooks.pdf
I got a reply from Amazon:
We reviewed your report and determined that it is incomplete. We cannot
take action on or complete any of your requests. Please resubmit your
report with all the required information as listed below.


-- Identification of the specific content on Amazon believed to be
infringing, by ASIN or URL. If your report is about specific seller
listings, please provide a list of sellers. If your report is about
text or images on a page describing a product, please identify those
images or that text. If your report is that the entire page or product
sold via that page infringes, please let us know.


-- A statement by you that you have a good-faith belief that the use of
the infringing content is not authorized by the rights owner, its
agent, or the law.


-- A statement by you, made under penalty of perjury, that the [above]
information in your notice is accurate and that you are the rights
owner or authorized to act on the rights owner's behalf.


All notices of intellectual property infringement must include:
-- The name and email address of the person submitting the notice, plus
any additional contact details.
-- The rights owner name, if the notice is submitted by an agent of the
rights owner.
-- Identification of the intellectual property right asserted, by
registration number, if applicable.
-- Identification of the specific content on Amazon believed to be
infringing, by ASIN or URL.
-- Statement that the information in the notice is accurate.
-- Statement that the submitter is authorized to act on behalf of the
rights owner and has a good-faith belief that the use of the content is
not authorized by the rights owner, its agent, or the law.

Complaint ID: 966376901

On Thu, 2017-06-01 at 02:32 -0700, J. Randall Hunt wrote:
> This is what I meant:
> 
> "I have attached a document listing the books confirmed to be
> 
> plagiarised along with the titles used by Seyed,"
> 
> The document with the list of confirmed plagiarized articles.
> 
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
> 
>   
>   
> 
> 
> 
> 
> 
> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
> 5493e4bb","name":"GitHub"},"entity":{"external_key":"github/karlsegui
> n/the-little-mongodb-book","title":"karlseguin/the-little-mongodb-
> book","subtitle":"GitHub repository","main_image_url":"https://cloud.
> githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
> 7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
> .com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
> b52498112777.png","action":{"name":"Open in
> GitHub","url":"https://github.com/karlseguin/the-little-mongodb-
> book"}},"updates":{"snippets":[{"icon":"PERSON","message":"@ranman in
> #46: This is what I meant:\r\n\"I have attached a document listing
> the books confirmed to be\r\nplagiarised along with the titles used
> by Seyed,\"\r\n\r\nThe document with the list of confirmed
> plagiarized articles."}],"action":{"name":"View
> Issue","url":"https://github.com/karlseguin/the-little-mongodb-
> book/issues/46#issuecomment-305441392"}}}

This basically says that I can complain about my book, but not about the other 19 as I am not "authorized to act on behalf of the rights owner"
Jan-- 
Dr Jan Newmarch,
Director of Higher Education (Business & ICT) @ Box Hill,
Adjunct Professor @ University of Canberra

P 61 3 9286 9971
M +61 4 0117 0509
F 61 3 9286 9100
W www.boxhill.edu.au
W jan.newmarch.name
E j.newmarch@boxhill.edu.au
E jan@newmarch.name

**Comment by ranman** [comment]
Ok I'm working on getting this all shut down and making sure we can detect this kind of stuff in the future.

**Comment by asya999** [comment]
Looks like it's been removed.
