### ISSUE TITLE
Another Japanese version from latest document

### ISSUE THREAD

**Issue by Makopo** [karlseguin/the-little-mongodb-book#47]
I just let you know that I wrote another Japanese version based on current latest document 7050b94453510325561694122e24af495d9c91a3 today.

https://github.com/Makopo/the-little-mongodb-book/tree/master/ja

The distribution(front) page is here:
https://github.com/Makopo/the-little-mongodb-book/wiki

Thank you.

**Comment by karlseguin** [comment]
Thanks, I updated the readme :)
