### ISSUE TITLE
Remark to chapter 5

### ISSUE THREAD

**Issue by pythononwheels** [karlseguin/the-little-mongodb-book#48]
Hi,

in chapter 5 you write: (Paragraph: When  to use MongoDB

> With that said, I'm hopeful that what you've seen so far has made you see MongoDB as a general solution. It's been mentioned a couple times that document-oriented databases share a lot in common with relational databases. Therefore, rather than tiptoeing around it, let's simply state that MongoDB should be seen as a direct alternative to relational databases. Where one might see Lucene as enhancing a relational database with full text indexing, or Redis as a persistent key-value store, MongoDB is a central repository for your data.

I think it is a good Idea to add some remark to Transactions here. The concept for Data modeling are comparable (embedded vs relations) etc but I think ACID vs eventual consistency is really a difference where you cannot take one or the other as valid alternatives. This is nothing more than a footnote but I think it might be useful to bring that to peoples minds...

Kind regards,
Klaas

**Comment by pythononwheels** [comment]
I just saw that also in chapter 5 there is a paragraph about transactions.
So it might be an option to link to that in the above section..

> 
> ## Transactions ##
> MongoDB doesn't have transactions. It has two alternatives, one which is great but with limited use, and the other that is cumbersome but flexible....

**Comment by asya999** [comment]
Since MongoDB now has transactions, this issue can probably be closed (I'm working on updating the text for the latest version).
