### ISSUE TITLE
Just finished the german translation of the little mongodb book

### ISSUE THREAD

**Issue by pythononwheels** [karlseguin/the-little-mongodb-book#49]
Hi, I just finished the german translation of [the little mongodb book ](https://github.com/pythononwheels/the-little-mongodb-book/tree/master/de)

Anyone please review it for spelling, grammar and text flow.. 

@karl:  Anything planned or needed for 3.x changes ..
    the basics haven't changed but maybe some extensions could be added.

**Comment by karlseguin** [comment]
Thanks. I updated the readme to point to it. I don't plan on updating the book. MongoDB themselves updated it for 2.6. Maybe they'll do the same.
