### ISSUE TITLE
PDF generation has some automatic chapter numbering artifacts/issues

### ISSUE THREAD

**Issue by cleary** [karlseguin/the-little-mongodb-book#50]
Hi, 
Thanks for the book - I've been reading through the PDF version and noticed it's got some chapter numbering inconsistencies:

![image](https://user-images.githubusercontent.com/2577966/39626263-8b0c644a-4fe4-11e8-9b4c-eaed1e7fb6b9.png)

Best as I can tell, it has to do with the auto-generation determining that the About, Introduction, and Getting Started sections are chapters, so they've been numbered accordingly (and incorrectly). So when you begin at Chapter 1, the PDF thinks you're already 3 chapters in...
![image](https://user-images.githubusercontent.com/2577966/39626345-d9ccee92-4fe4-11e8-8efb-c3e9eaa5e4ff.png)
![image](https://user-images.githubusercontent.com/2577966/39626376-fc4daf6a-4fe4-11e8-9241-e0d0c4fdf617.png)

etc

**Comment by asya999** [comment]
I've resolved it by using pandoc option --top-level-division=section

**Comment by karlseguin** [comment]
Thanks
