### ISSUE TITLE
Chapter 4, No Joins, $lookup operator

### ISSUE THREAD

**Issue by acfasj** [karlseguin/the-little-mongodb-book#52]
$lookup performs a left outer join, shall we update the article?
https://docs.mongodb.com/manual/reference/operator/aggregation/lookup/index.html

**Comment by karlseguin** [comment]
I'm not really up to maintaining changes. What `$lookup` provides is far from the full capabilities of a relational database. I think most people expect inner joins on simple queries. This is only a left outer join within the aggregation pipeline.

If I was maintaining large changes, I'd rather more information be added in the aggregation section.
